image: docker:latest

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  REPOSITORY: "${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}"
  PS_VERSION: "6.1.0"
  OS_VERSION: "ubuntu-18.04"

before_script:
  - echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin

.build_template: &build_definition
  stage: build
  script:
    - VARIANT="${PS_VERSION}-${OS_VERSION}-${CI_JOB_NAME}"
    - docker pull "${REPOSITORY}:${VARIANT}" || true
    - docker build
        -t "${REPOSITORY}:${VARIANT}"
        --cache-from "${REPOSITORY}:${VARIANT}"
        --build-arg IMAGE="mcr.microsoft.com/${CI_PROJECT_NAME}:${PS_VERSION}-${OS_VERSION}"
        "${CI_JOB_NAME}/"
    - if [ "${LATEST}" = true ]; then
        docker tag "${REPOSITORY}:${VARIANT}" "${REPOSITORY}:${CI_JOB_NAME}";
      fi
    - docker images
    - docker push "${REPOSITORY}"

git:
  variables:
    IMAGE: powershell:6.1.0-rc.1-ubuntu-18.04
    LATEST: "true"
  <<: *build_definition

after_script:
  - docker logout