image: docker:latest

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  REPOSITORY: "${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}"

before_script:
  - echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin

.build_template: &build_definition
  stage: build
  script:
    - IMAGE="mcr.microsoft.com/${CI_PROJECT_NAME}:${PS_VERSION}-${OS}-${OS_VERSION}"
    - VARIANT="${PS_VERSION}-${OS}-${OS_VERSION}-${CI_JOB_NAME}"
    - docker pull "${REPOSITORY}:${VARIANT}" || true
    - docker build
        --cache-from "${REPOSITORY}:${VARIANT}"
        -t "${REPOSITORY}:${VARIANT}"
        --build-arg IMAGE="${IMAGE}"
        "${CI_JOB_NAME}/"
    - if [ "${DEFAULT}" = true ]; then
        docker tag "${REPOSITORY}:${VARIANT}" "${REPOSITORY}:${CI_JOB_NAME}";
      fi
    - docker images
    - docker push "${REPOSITORY}"

git:
  variables:
    PS_VERSION: "6.1.0"
    OS: "ubuntu"
    OS_VERSION: "18.04"
    DEFAULT: "true"
  <<: *build_definition

after_script:
  - docker logout